### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by MannyMeadows** [fiatjaf/ipfs-dropzone#1]
I've been looking for a repo like this for ages. Any luck getting it to bundle with browserify? 
Kudos on Filemap by the way, brilliant idea.

**Comment by fiatjaf** [comment]
Well, it should work with browserify without any special setup, I guess. [That's how I'm using it](https://github.com/fiatjaf/filemap.xyz/blob/4f033605da5eb86d867ed6ce2dec029930928e77/package.json#L8) anyway.

Have you tried it and gotten an error?

**Comment by MannyMeadows** [comment]
Of course, pardon me. I had misunderstood a node-gyp error, I thought it related to README.md#58, and it didn't.

All good now, thanks.
