### ISSUE TITLE
How to automatically pin uploaded files to other nodes?

### ISSUE THREAD

**Issue by faddat** [fiatjaf/ipfs-dropzone#3]
I'd like to use this but need to ensure that the uploaded files get pinned to one of my persistent IPFS nodes.  

Any ideas?

**Comment by fiatjaf** [comment]
This is something you must do on your nodes side.

You could call an URL from your JS app that will trigger a `pin` command from your nodes.

**Comment by faddat** [comment]
Thanks so much for your help, I'll close the issue :).
